<a href="https://colab.research.google.com/github/darshanvjani/Awesome-Pytorch/blob/main/Complete_Pytorch_Tensor_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch

In [5]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]])

In [6]:
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


We can set the type of the tensor as well.

In [7]:
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

We can set where this value will be on.

In [8]:
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device="cpu")

tensor([[1., 2., 3.],
        [4., 5., 6.]])

we can add requires gradient as well which can br used while backprop.

In [9]:
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device="cpu",requires_grad=True)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

we can write it as this as well to make the cpu/gpu memory allocation automatic.

In [10]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=device,requires_grad=True)

In [11]:
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


Other Innitialization Methods

In [12]:
x = torch.empty(size=(3,3))
print(x)

tensor([[-1.3403e-26,  3.0771e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  1.4013e-45],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22]])


In [13]:
#For Zero Matrix
x = torch.zeros((3,3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


to initialize values with uniform distribution randomly

In [14]:
x = torch.rand((3,3))
print(x)

tensor([[0.8301, 0.6753, 0.6753],
        [0.2676, 0.9026, 0.1829],
        [0.2190, 0.4427, 0.6417]])


to initialize value with all the ones

In [15]:
x = torch.ones((3,3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


to initilize identity matrix

In [16]:
torch.eye(5,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
torch.arange(start=0,end=5,step=1)

tensor([0, 1, 2, 3, 4])

In [18]:
torch.linspace(start=0.1,end=1,steps=10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [19]:
torch.empty((1,5)).normal_(mean=0,std=1)

tensor([[ 2.1287,  1.3552, -0.9480,  0.4848, -3.3666]])

**How to Initialize and convert tensor into different **

In [20]:
tensor = torch.tensor([[1,2,3],[4,5,6]])

In [21]:
print(tensor) 
print(tensor.short()) #int16
print(tensor.long())  #int64
print(tensor.half())  #float16
print(tensor.float()) #float32
print(tensor.double())  #float64

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int16)
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [22]:
tensor.data_ptr() == tensor.long().data_ptr() #tensor.long() is the same as tensor (both are int 64)

True

**Conversation between tensor and Numpy Array**



In [23]:
#From Numpy to Tensor
import numpy as np
array = np.zeros((5,5))
tensor_t = torch.from_numpy(array)

In [24]:
#From Tensor to Numpy
numpy_array_back = tensor_t.numpy()

**Tensor Math & Comperazion Operation**

works only if the shape of both the tensor is same

In [25]:
x = torch.tensor([[1,2,3]])
y = torch.tensor([[3,2,1]])

In [26]:
z = x + y
print(z)

tensor([[4, 4, 4]])


In [27]:
z = x - y
print(z)

tensor([[-2,  0,  2]])


In [28]:
z = torch.true_divide(x,y)
print(z)

tensor([[0.3333, 1.0000, 3.0000]])


Adding Inplace

In [49]:
tensor_t = torch.rand((1,3))
print(tensor_t)
tensor_t.add_(x)
print(tensor_t)
###you can also used this to keep the pointer same
tensor_t+=x

tensor([[0.7551, 0.1161, 0.1025]])
tensor([[ 1.7551, -0.8839,  1.1025]])


In [61]:
x = torch.rand((1,3))

Element wise Exponential

In [62]:
x.pow_(3) #keeping the pointer same
x
x = x ** 3 #copy
x

tensor([[1.7165e-01, 3.6534e-14, 8.0311e-04]])

Matrix Multiplication

In [67]:
t1 = torch.rand((1,3))
t2 = torch.rand((3,5))
print(torch.mm(t1,t2))

tensor([[0.7568, 0.7168, 0.5614, 0.5167, 0.7598]])


Matrix Power

In [77]:
t1 = torch.tensor([[1,2],[2,1]],dtype=float)
# t2 = torch.rand((1,3))
print(t1)
t1 = t1.mm(t1)
print(t1)

tensor([[1., 2.],
        [2., 1.]], dtype=torch.float64)
tensor([[5., 4.],
        [4., 5.]], dtype=torch.float64)


Element Wise Multiplication & Dot Product



In [80]:
#Both the tensor has to have same shape for doing element wise mul
x = torch.tensor([1,2,3])
y = torch.tensor([1,2,3])
z = x * y
print(z)

tensor([1, 4, 9])


In [81]:
#Dot
z = x.dot(y)
z

tensor(14)

Batch Wise Multiplication

In [84]:
batch = 32
n = 10
m = 20
p = 30
x = torch.rand((batch,n,m))
y = torch.rand((batch,m,p))
z = torch.bmm(x,y)
print(z.shape) ##shape (batch,n,p)

torch.Size([32, 10, 30])
