<a href="https://colab.research.google.com/github/darshanvjani/Awesome-Pytorch/blob/main/Complete_Pytorch_Tensor_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]])

In [3]:
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


We can set the type of the tensor as well.

In [4]:
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

We can set where this value will be on.

In [5]:
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device="cpu")

tensor([[1., 2., 3.],
        [4., 5., 6.]])

we can add requires gradient as well which can br used while backprop.

In [6]:
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device="cpu",requires_grad=True)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

we can write it as this as well to make the cpu/gpu memory allocation automatic.

In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=device,requires_grad=True)

In [8]:
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


Other Innitialization Methods

In [9]:
x = torch.empty(size=(3,3))
print(x)

tensor([[1.8492e+15, 3.0746e-41, 3.3631e-44],
        [0.0000e+00,        nan, 1.4013e-45],
        [1.1578e+27, 1.1362e+30, 7.1547e+22]])


In [10]:
#For Zero Matrix
x = torch.zeros((3,3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


to initialize values with uniform distribution randomly

In [11]:
x = torch.rand((3,3))
print(x)

tensor([[0.2499, 0.3792, 0.8804],
        [0.0703, 0.8967, 0.2718],
        [0.7674, 0.1197, 0.1843]])


to initialize value with all the ones

In [12]:
x = torch.ones((3,3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


to initilize identity matrix

In [13]:
torch.eye(5,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
torch.arange(start=0,end=5,step=1)

tensor([0, 1, 2, 3, 4])

In [15]:
torch.linspace(start=0.1,end=1,steps=10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [16]:
torch.empty((1,5)).normal_(mean=0,std=1)

tensor([[ 0.4924, -0.8769, -0.8223,  0.4643,  0.9484]])

**How to Initialize and convert tensor into different **

In [17]:
tensor = torch.tensor([[1,2,3],[4,5,6]])

In [18]:
print(tensor) 
print(tensor.short()) #int16
print(tensor.long())  #int64
print(tensor.half())  #float16
print(tensor.float()) #float32
print(tensor.double())  #float64

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int16)
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [19]:
tensor.data_ptr() == tensor.long().data_ptr() #tensor.long() is the same as tensor (both are int 64)

True

**Conversation between tensor and Numpy Array**



In [20]:
#From Numpy to Tensor
import numpy as np
array = np.zeros((5,5))
tensor_t = torch.from_numpy(array)

In [21]:
#From Tensor to Numpy
numpy_array_back = tensor_t.numpy()

**Tensor Math & Comperazion Operation**

works only if the shape of both the tensor is same

In [22]:
x = torch.tensor([[1,2,3]])
y = torch.tensor([[3,2,1]])

In [23]:
z = x + y
print(z)

tensor([[4, 4, 4]])


In [24]:
z = x - y
print(z)

tensor([[-2,  0,  2]])


In [25]:
z = torch.true_divide(x,y)
print(z)

tensor([[0.3333, 1.0000, 3.0000]])


Adding Inplace

In [26]:
tensor_t = torch.rand((1,3))
print(tensor_t)
tensor_t.add_(x)
print(tensor_t)
###you can also used this to keep the pointer same
tensor_t+=x

tensor([[0.8572, 0.1059, 0.7057]])
tensor([[1.8572, 2.1059, 3.7057]])


In [27]:
x = torch.rand((1,3))

Element wise Exponential

In [28]:
x.pow_(3) #keeping the pointer same
x
x = x ** 3 #copy
x

tensor([[1.6087e-07, 4.7938e-06, 4.4273e-01]])

Matrix Multiplication

In [29]:
t1 = torch.rand((1,3))
t2 = torch.rand((3,5))
print(torch.mm(t1,t2))

tensor([[0.6777, 0.5457, 0.8486, 0.5578, 0.6357]])


Matrix Power

In [30]:
t1 = torch.tensor([[1,2],[2,1]],dtype=float)
# t2 = torch.rand((1,3))
print(t1)
t1 = t1.mm(t1)
print(t1)

tensor([[1., 2.],
        [2., 1.]], dtype=torch.float64)
tensor([[5., 4.],
        [4., 5.]], dtype=torch.float64)


Element Wise Multiplication & Dot Product



In [31]:
#Both the tensor has to have same shape for doing element wise mul
x = torch.tensor([1,2,3])
y = torch.tensor([1,2,3])
z = x * y
print(z)

tensor([1, 4, 9])


In [32]:
#Dot
z = x.dot(y)
z

tensor(14)

Batch Wise Multiplication

In [33]:
batch = 32
n = 10
m = 20
p = 30
x = torch.rand((batch,n,m))
y = torch.rand((batch,m,p))
z = torch.bmm(x,y)
print(z.shape) ##shape (batch,n,p)

torch.Size([32, 10, 30])


Math Operations

In [34]:
x = torch.tensor([[1,2,3],[4,5,6]])
print("X:",x)
print()
print("X_sum:",x.sum(dim=1))
print()
print("X_max:",x.max(dim=1))
print()
print("X_min",x.min(dim=0))
print()
print("Abs Value:",x.abs())

X: tensor([[1, 2, 3],
        [4, 5, 6]])

X_sum: tensor([ 6, 15])

X_max: torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))

X_min torch.return_types.min(
values=tensor([1, 2, 3]),
indices=tensor([0, 0, 0]))

Abs Value: tensor([[1, 2, 3],
        [4, 5, 6]])


In [35]:
print(x.argmax(dim=0))  #colomn
print(x.argmin(dim=1))   #row

tensor([1, 1, 1])
tensor([0, 0])


In [36]:
y = torch.tensor([[1,2,3],[4,5,7]])
print(x.eq(y)) #check if elements of x is equal to y

tensor([[ True,  True,  True],
        [ True,  True, False]])


In [37]:
x.shape #2 rows , 3 colomns , dim=0 -> colomn wise, dim=1 -> row wise

torch.Size([2, 3])

In [38]:
y[0,1] = 8
y

tensor([[1, 8, 3],
        [4, 5, 7]])

In [39]:
print(y.sort(dim=1,descending=False)) #dim 0 -> colomn wise , dim = 1 -> row wise

torch.return_types.sort(
values=tensor([[1, 3, 8],
        [4, 5, 7]]),
indices=tensor([[0, 2, 1],
        [0, 1, 2]]))


In [40]:
print(y.clamp(min=1,max=5)) #clamp all the value which are less then 1 -> 1, and all the values which are greater then 5 -> 5

tensor([[1, 5, 3],
        [4, 5, 5]])


In [41]:
bool_t = torch.tensor([1,0,1,1,1],dtype=bool)
print(bool_t.any()) #check if any value is positive
print(bool_t.all())  #check if all value is positive

tensor(True)
tensor(False)


  Tensor Indexing

In [42]:
batch_size = 10
r = 3
c = 4
ten = torch.rand((batch_size,r,c),dtype=float)
print(ten[0,:]) #first element of the batch

tensor([[0.0718, 0.0577, 0.7301, 0.5408],
        [0.3237, 0.1180, 0.4876, 0.7995],
        [0.2852, 0.5456, 0.7156, 0.2359]], dtype=torch.float64)


In [43]:
print(ten[:,0])

tensor([[0.0718, 0.0577, 0.7301, 0.5408],
        [0.4888, 0.3297, 0.9110, 0.5790],
        [0.2206, 0.1253, 0.9380, 0.2229],
        [0.6641, 0.8720, 0.4705, 0.9800],
        [0.2389, 0.2396, 0.3543, 0.1141],
        [0.6308, 0.2651, 0.2008, 0.2300],
        [0.2878, 0.1549, 0.9870, 0.4000],
        [0.5205, 0.6863, 0.0027, 0.9905],
        [0.2092, 0.1701, 0.8879, 0.3783],
        [0.2699, 0.0611, 0.3604, 0.9102]], dtype=torch.float64)


In [44]:
ten[3,:2,:3]

tensor([[0.6641, 0.8720, 0.4705],
        [0.5332, 0.2010, 0.5299]], dtype=torch.float64)

In [45]:
##Fancy Indexing
indexing = [1,2]
print(ten[indexing].shape)

torch.Size([2, 3, 4])


In [46]:
##Advance Index Operation
x = torch.tensor([[1,2,4,6,8,9,0],[1,2,4,6,8,9,0]])
print(x[(x >= 2) & (x <= 6)]) #elements which are greater then 2 or less then 6
print(x[x==8]) #elements which are exactly 8
print(x[x!=8])
print(x[x.remainder(2)==0]) #to get odd/even numbers

tensor([2, 4, 6, 2, 4, 6])
tensor([8, 8])
tensor([1, 2, 4, 6, 9, 0, 1, 2, 4, 6, 9, 0])
tensor([2, 4, 6, 8, 0, 2, 4, 6, 8, 0])


In [47]:
#Some USEFULL Operation
print(torch.where(x>5,x,1)) #if X>5 -> x else -> 1

tensor([[1, 1, 1, 6, 8, 9, 1],
        [1, 1, 1, 6, 8, 9, 1]])


In [48]:
#to check the unique number of elements in tensor
print(torch.tensor([1,1,2,3,1,4,5,67,3,6]).unique())

tensor([ 1,  2,  3,  4,  5,  6, 67])


In [50]:
#to check the total number of elements in the tensor
print(torch.tensor([[1,1,2,3,1,4,5,67,3,6],[1,2,3,4,5,6,7,8,90,1]]).numel())

20


In [51]:
#to find the total dimension of the tensor
print(torch.tensor([[1,2,3],[4,5,6],[7,8,9]]).ndimension())

2


**Tensor Reshaping**

reshape

In [54]:
x = torch.arange(10)
x.shape

torch.Size([10])

In [57]:
x_1x10 = x.reshape(1,10)
x_1x10.shape

torch.Size([1, 10])

In [89]:
x = torch.arange(9)
x.shape

torch.Size([9])

In [90]:
x_3x3 = x.reshape(3,3)
x.data_ptr() == x_3x3.data_ptr()

True

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [92]:
#transpose
x_3x3 = x_3x3.t()
x.data_ptr() == x_3x3.data_ptr()

True

view

In [93]:
x = torch.arange(9)
x.shape

torch.Size([9])

In [94]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [95]:
x_3x3 = x.view(3,3)
x.data_ptr() == x_3x3.data_ptr()

True

In [96]:
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [97]:
x_3x3 = x_3x3.t()

In [104]:
x.data_ptr() == x_3x3.data_ptr()

False

In [99]:
x_3x3.view(9) #problem while using view

RuntimeError: ignored

In [100]:
x_3x3.contiguous().view(9) #you can solve it by using contiguous or use reshape to be on the safe side

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [103]:
x = torch.rand((2,3))
y = torch.rand((2,3))
z = torch.cat((x,y),dim=0) #dim=0 -> row wise
q = torch.cat((x,y),dim=1) #dim=1 -> colomn wise
print(z)
print(q)

tensor([[0.6905, 0.4606, 0.9696],
        [0.8167, 0.5710, 0.9757],
        [0.0558, 0.4207, 0.4283],
        [0.4934, 0.4952, 0.9301]])
tensor([[0.6905, 0.4606, 0.9696, 0.0558, 0.4207, 0.4283],
        [0.8167, 0.5710, 0.9757, 0.4934, 0.4952, 0.9301]])


In [113]:
batch = 64
x = torch.rand(batch,5,10)
x.shape

torch.Size([64, 5, 10])

In [115]:
z = x.reshape(batch,10,-1)
z.shape

torch.Size([64, 10, 5])

In [116]:
z = x.reshape(batch,-1)
z.shape

torch.Size([64, 50])

In [117]:
z = x.permute(1,0,2)
z.shape

torch.Size([5, 64, 10])

Unsqueeze & Squeeze Operation

In [126]:
x = torch.arange(10)  #1 dim ,0 index
z = x.unsqueeze(1)  #unsquuze on 2nd dim or 1 index
z.shape

torch.Size([10, 1])

In [127]:
z

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [128]:
x.shape

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
z = z.squeeze(1)
z

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])