<a href="https://colab.research.google.com/github/darshanvjani/Awesome-Pytorch/blob/main/Initializing_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]])

In [3]:
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


We can set the type of the tensor as well.

In [4]:
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

We can set where this value will be on.

In [5]:
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device="cpu")

tensor([[1., 2., 3.],
        [4., 5., 6.]])

we can add requires gradient as well which can br used while backprop.

In [6]:
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device="cpu",requires_grad=True)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

we can write it as this as well to make the cpu/gpu memory allocation automatic.

In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=device,requires_grad=True)

In [8]:
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


Other Innitialization Methods

In [9]:
x = torch.empty(size=(3,3))
print(x)

tensor([[-9.0858e+33,  3.0753e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  1.4013e-45],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22]])


In [10]:
#For Zero Matrix
x = torch.zeros((3,3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


to initialize values with uniform distribution randomly

In [11]:
x = torch.rand((3,3))
print(x)

tensor([[0.2061, 0.1363, 0.0959],
        [0.2849, 0.2748, 0.6789],
        [0.6810, 0.1089, 0.3439]])


to initialize value with all the ones

In [12]:
x = torch.ones((3,3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


to initilize identity matrix

In [13]:
torch.eye(5,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
torch.arange(start=0,end=5,step=1)

tensor([0, 1, 2, 3, 4])

In [15]:
torch.linspace(start=0.1,end=1,steps=10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [16]:
torch.empty((1,5)).normal_(mean=0,std=1)

tensor([[ 1.7047,  0.4445, -1.0532, -0.0599,  1.4764]])

**How to Initialize and convert tensor into different **

In [18]:
tensor = torch.tensor([[1,2,3],[4,5,6]])

In [21]:
print(tensor) 
print(tensor.short()) #int16
print(tensor.long())  #int64
print(tensor.half())  #float16
print(tensor.float()) #float32
print(tensor.double())  #float64

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int16)
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [32]:
tensor.data_ptr() == tensor.long().data_ptr() #tensor.long() is the same as tensor (both are int 64)

True